export default {
  ADD_EVENT: "ADD_EVENT",
  GET_EVENT_LIST: "GET_EVENT_LIST",
  ADD_EVENT_LIST: "ADD_EVENT_LIST",
  SELECT_EVENT: "SELECT_EVENT",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
};